service: cloudsearch-s3-handler
frameworkVersion: '3'
configValidationMode: error
plugins:
  - serverless-webpack
  - serverless-plugin-existing-s3
  - serverless-plugin-scripts

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-888294ed
    subnetIds:
      - subnet-f2c2dfda # us-east-1a
      - subnet-1508db62 # us-east-1b
      - subnet-3fd94266 # us-east-1c
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: apps@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - CloudDearch:Document
          Resource: ${env:CLOUDSEARCH_DOMAIN_ARN}
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListBucket
            - s3:GetBucketNotification
            - s3:PutBucketNotification
          Resource:
            - arn:aws:s3:::${env:S3_BUCKET_NAME}
            - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
  layers:
    - arn:aws:lambda:us-east-1:072686360478:layer:node-16_14_2:1
  environment: ${file(env.js)}

package:
  individually: true
  patterns:
    - '!.webpack/**'
    - '!test/**'
    - '!**/*.test.js'
    - '!.deployment/**'

custom:
  scripts:
    hooks:
      # Run s3deploy command
      'aws:deploy:finalize:cleanup': 'npx serverless s3deploy'
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
    excludeRegex: \.ts|test|\.map
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

resources:
  extensions:
    IamRoleLambdaExecution:
      Properties:
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess

functions:
  s3event:
    handler: handlers/event.handler
    events:
      - existingS3:
          # See https://www.npmjs.com/package/serverless-plugin-existing-s3
          bucket: ${env:S3_BUCKET_NAME}
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .html
